### ISSUE TITLE
Issue with spm_defaults.m outputs

### ISSUE THREAD

**Issue by vineetraichur** [vineetraichur/LiFE_ACNN_Pipeline#2]
![image](https://user-images.githubusercontent.com/29384408/27055359-251498cc-4f92-11e7-94cd-2209ee71e50b.png)

**Comment by francopestilli** [comment]
@vineetraichur try adding to the path spm/8 instead of 12

**Comment by vineetraichur** [comment]
spm8 worked well and Step 1 executed successfully. I had come across a similar issue in Step 2, which has also been resolved now.
